# Example boards configuration for SoC Validation Infrastructure
# This file defines the available boards for test execution

boards:
  # Lab Site A boards - Direct telnet endpoints
  - board_id: soc-a-001
    soc_family: socA
    board_ip: 10.1.1.101
    telnet_port: 23
    pdu_host: pdu-a.lab.local
    pdu_outlet: 1
    location: lab-site-a
    health_status: healthy

  - board_id: soc-a-002
    soc_family: socA
    board_ip: 10.1.1.102
    telnet_port: 23
    pdu_host: pdu-a.lab.local
    pdu_outlet: 2
    location: lab-site-a
    health_status: healthy

  - board_id: soc-a-003
    soc_family: socA
    board_ip: 10.1.1.103
    telnet_port: 23
    pdu_host: pdu-a.lab.local
    pdu_outlet: 3
    location: lab-site-a
    health_status: healthy

  # Lab Site B boards - Direct telnet endpoints
  - board_id: soc-b-001
    soc_family: socB
    board_ip: 10.1.2.101
    telnet_port: 23
    pdu_host: pdu-b.lab.local
    pdu_outlet: 1
    location: lab-site-b
    health_status: healthy

  - board_id: soc-b-002
    soc_family: socB
    board_ip: 10.1.2.102
    telnet_port: 23
    pdu_host: pdu-b.lab.local
    pdu_outlet: 2
    location: lab-site-b
    health_status: healthy

  # Lab Site C boards - More boards for larger deployment
  - board_id: soc-c-001
    soc_family: socC
    board_ip: 10.1.3.101
    telnet_port: 23
    pdu_host: pdu-c.lab.local
    pdu_outlet: 1
    location: lab-site-c
    health_status: healthy

  - board_id: soc-c-002
    soc_family: socC
    board_ip: 10.1.3.102
    telnet_port: 23
    pdu_host: pdu-c.lab.local
    pdu_outlet: 2
    location: lab-site-c
    health_status: healthy
    
  - board_id: soc-c-003
    soc_family: socC
    board_ip: 10.1.3.103
    telnet_port: 23
    pdu_host: pdu-c.lab.local
    pdu_outlet: 3
    location: lab-site-c
    health_status: healthy